const QUERY_VIEW_USER = {
  _id: 1,
  firstName: 1,
  lastName: 1,
  fullName: 1,
  email: 1,
  phone: 1,
  www: 1,
  vertiedAt: 1,
  avatar: 1,
  ip: 1,
  device: 1,
  browser: 1,
  zalo: 1,
  facebook: 1,
  telegram: 1,
  guest: 1,
  statusChat: 1,
  deviceCount: 1,
  country: 1,
  region: 1,
  timezone: 1,
  city: 1,
  os: 1,
  query: 1,
  regionName: 1,
  google: 1,
  facebookInfo: 1,
  uuid: 1,
  userDetail: 1,
  createdAt: 1,
  updatedAt: 1,
  password: 1,
};
const QUERY_VERIFY_USER = {
  _id: 1,
  password: 1,
};
export { QUERY_VIEW_USER, QUERY_VERIFY_USER };
